### ISSUE TITLE
Shortcut ?

### ISSUE THREAD

**Issue by Nebula-Spark** [avocode/electron-windows-autoupdate#7]
Hi ,
Thanks For the repo, Everything works like charm What u mentioned in the docs , 
But I just need a help , the default installation is on the app data /roaming in windows , is it possible to change the directory ? 

and whenever it updates the apps changes to new version adding new folder with version number ,
 is there anyway to be a static folder and exe the app should be  ?
i am just a newbie it would be great if u can help me on this ,
I Need a static exe path of the app , not the dynamic app exe every time the app changes. is there any solution for it ?

**Comment by vojtatranta** [comment]
I have no idea...

What do you need static `.exe` path for?

**Comment by Nebula-Spark** [comment]
I mean  A Full App At static folder like , other windows apps. example like installing games it would be on static folder and the exe path never changes

Because I want to open this   app through another app ,  like  using electron shell API

shell.openItem("C:\Users\machine1\AppData\Local\mynewapp.exe")

but all i see a updater.exe in that folder and itz not opening the app 
and in the version folder, i can find the exe but whenever the app updates it creates a new folder !

**Comment by vojtatranta** [comment]
That's not how you open things via path to executable.

Better idea is to register a protocol. And then you do just this `yourProtocol://my-parameters/`.

This should work with windows too.

Here is a guide how to use custom protocols: https://glebbahmutov.com/blog/electron-app-with-custom-protocol/

If you use custom protocol, you don't need to care where executable is, OS will handle it for you. That's the right way of doing it.
