### ISSUE TITLE
Rune Time Error! When Updates Server Stopped

### ISSUE THREAD

**Issue by Nebula-Spark** [avocode/electron-windows-autoupdate#8]
When The Updater Server is Stopped,  Getting The following Error  when launching the app . But App works fine .

![proceess error](https://cloud.githubusercontent.com/assets/2277794/23238838/ebf9f518-f989-11e6-829f-826e9c88f00f.jpg)

Is there anyway to ignore this error , to avoid this dialog?

**Comment by vojtatranta** [comment]
Auto updater cannot connect to the update server. That's the problem and that's what dialog says.

**Comment by Nishanth2** [comment]
@vojtatranta  So is there anyway to Avoid this Error ?

**Comment by vojtatranta** [comment]
sorry @Nishanth2 that's not an issue of this repo, the error is clear. Keep this issue closed, thanks :)
